version: '3'
services:
  web:
    stdin_open: true
    build:
      context: . #current directory
      dockerfile: Dockerfile
      #rebuild with docker-compose down && docker-compose up --build
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
        #current folder outside container to /app folder inside container
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    #dash is an array
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]